### ISSUE TITLE
Server started on `http://:::3333`

### ISSUE THREAD

**Issue by whitneyit** [nkt/gulp-serve#15]
On Line [68](https://github.com/nkt/gulp-serve/blob/697db1cdb4840a1f1aef4a20988e03e093807867/index.js#L68) and [70](https://github.com/nkt/gulp-serve/blob/697db1cdb4840a1f1aef4a20988e03e093807867/index.js#L70) of [index.js](https://github.com/nkt/gulp-serve/blob/697db1cdb4840a1f1aef4a20988e03e093807867/index.js), there is a reference to `config.hostname`.

If `hostname` is not set, it defaults to `::`

**Comment by nkt** [comment]
So?

**Comment by whitneyit** [comment]
The `hostname` is not explained in the readme. If it is not set, a default of localhost seems reasonable.
