### ISSUE TITLE
to pass array of middlewares

### ISSUE THREAD

**Issue by pajooh** [nkt/gulp-serve#6]
is it possible?

**Comment by dciccale** [comment]
You cant do that already.

**Comment by LinusU** [comment]
@dciccale what is it that you can't do?

Passing `middlewares` as an array works great, have you even tried it?

**Comment by dciccale** [comment]
sorry i meant that you CAN do that already.

**Comment by dciccale** [comment]
this issue should be closed

**Comment by nkt** [comment]
@dciccale you're right.
